### ISSUE TITLE
oidc_authorization_code_flow does not work, and redirect_uri should be provided

### ISSUE THREAD

**Issue by nikkilocke** [rcbj/oauth2-oidc-debugger#5]
Thanks for writing this.

I am trying it out to see if my openid implementation works.

Using oidc_authorization_code_flow does not work.
There seems to be no code to retrieve the code from the uri so you can go on to the next step.

Also, I found it very difficult to work out what the redirect uri should be. I tried just /callback, but it seems a bit odd to me. The OAuth2 options (e.g. authorization_grant) seem to expect the parameters to be in window.location.hash, for some reason, instead of in query variables. But if I make the redirect url /callback#, it sort of works. Not sure why I should have to guess what the redirect uri is - surely it should be filled in automatically, as a read-only field?

Shouldn't the code also decode the oidc token returned as well?

**Comment by rcbjBlueMars** [comment]
The redirect URI that you register with your IdP for use with the debugger should be http;//localhost:3000/callback, unless you put some type of proxy in front of it or change the configuration.

If your IdP doesn't return an authorization code, that means the authentication step failed or there was some type of problem with the request to the authorization endpoint. What error message is returned from the authorization code endpoint?

**Comment by nikkilocke** [comment]
Thanks a million for getting back to me so quickly!
You are, of course, right - there was a bug in my code. 

When debugging your javascript I saw the calls to parseFragment (which seems to get values from the hash), and got confused.

I want to test if my jwt is signed correctly, too - might be a nice thing to add to the test suite?
