### ISSUE TITLE
Ruby 2.4.0 "invalid address" error in in6_addr

### ISSUE THREAD

**Issue by optiz0r** [rcbj/oauth2-oidc-debugger#6]
Hi,

Thank you for an amazingly useful tool!

I found the "Get Token" step failing with "invalid address" error, which looks to be ipv6 related. My machine did not have any ipv6 addresses, so not sure where the error was coming from, but looks to be a bug in ruby 2.4.0/2.4.1. supposedly fixed in 2.4.2 (not tested). I worked around it by downgrading to 2.3.0 in the Dockerfile.

Noting here in case anyone else runs into the same issue.

Thanks!
Ben

**Comment by rcbjBlueMars** [comment]
Thanks.

I will bump the ruby version listed in Dockerfile to 2.4.2. Need to test that and a few other small updates in the near future first.

**Comment by rcbjBlueMars** [comment]
Closing this since all ruby related code has been removed from the project. This should work with node.js.
