### ISSUE TITLE
Support for default IDP using Keycloak as Identity Broker

### ISSUE THREAD

**Issue by pigreco33** [rcbj/oauth2-oidc-debugger#7]
Can you add support to set extra parameters like _kc_idp_hint_ used by keycloak to choose the default brokered idp?

Here is the documentation: https://www.keycloak.org/docs/latest/server_admin/#default_identity_provider

Thanks

**Comment by rcbjBlueMars** [comment]
I created an online version of this tool. I added features that I haven't ported back to this repo. Check out [1]. It has the ability to add custom parameters to the calls for the authorization endpoint and token endpoints. Does that let you do what you need to?

Reference:
[1] https://tools.test.idptools.io/debugger.html
